version: "3.8"

networks:
  ecbackend:

services:
  auth-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest-ci
    hostname: auth-server
    environment:
      - LIVEKIT_JWT_PORT=6080
      - LIVEKIT_URL=wss://matrix-rtc.m.localhost/livekit/sfu
      - LIVEKIT_KEY=devkey
      - LIVEKIT_SECRET=secret
      - LIVEKIT_INSECURE_SKIP_VERIFY_TLS=YES_I_KNOW_WHAT_I_AM_DOING
    ports:
      - 6080:6080
    networks:
      - ecbackend
    restart: on-failure

  livekit:
    image: livekit/livekit-server:latest
    hostname: livekit-sfu
    command: --dev --config /etc/livekit.yaml
    ports:
      - 7880:7880/tcp
      - 7881:7881/tcp
      - 7882:7882/tcp
      - 50100-50200:50100-50200/udp
    volumes:
      - ./backend/dev_livekit.yaml:/etc/livekit.yaml:Z
    networks:
      - ecbackend
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    command: redis-server /etc/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./backend/redis.conf:/etc/redis.conf:Z
    networks:
      - ecbackend

  synapse:
    image: matrixdotorg/synapse:latest
    hostname: homeserver
    environment:
      - SYNAPSE_CONFIG_PATH=/data/cfg/homeserver.yaml
      - UID=0
      - GID=0
    volumes:
      - ./backend/synapse_tmp:/data:Z
      - ./backend/dev_homeserver.yaml:/data/cfg/homeserver.yaml:Z
    networks:
      - ecbackend

  element-web:
    image: ghcr.io/element-hq/element-web:develop
    pull_policy: always
    volumes:
      - ./backend/ew.test.config.json:/app/config.json:Z
    environment:
      - ELEMENT_WEB_PORT=8081
    ports:
      - 8081:8081
    networks:
      - ecbackend

  nginx:
    image: nginx:latest
    hostname: synapse.m.localhost
    volumes:
      - ./backend/dev_nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./backend/dev_tls_m.localhost.key:/root/ssl/key.pem:Z
      - ./backend/dev_tls_m.localhost.crt:/root/ssl/cert.pem:Z
    ports:
      - "443:443"
      - "8008:80"
      - "8448:8448"
      - "4443:443"
    depends_on:
      - synapse
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecbackend

  static-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: matrixrtc/static-site:latest
    ports:
      - 3000:80
    networks:
      - ecbackend
